version: 2.1
orbs:
  cypress: cypress-io/cypress@1.23.0
jobs:
  release:
    executor: cypress/browsers-chrome78-ff70
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release

workflows:
  build:
    jobs:
      - cypress/install:
          name: Install
          executor: cypress/browsers-chrome78-ff70

      - cypress/run:
          name: Electron tests
          requires:
            - Install
          executor: cypress/browsers-chrome78-ff70
          install-command: echo 'Nothing to install in this job'
          no-workspace: true

      - release:
          requires:
            - Electron tests
