version: 2.1
orbs:
  cypress: cypress-io/cypress@1.23.0
jobs:
  release:
    executor: cypress/browsers-chrome78-ff70
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome78-ff70
      - release:
          requires:
            - cypress/run
